### ISSUE TITLE
Allow user to specify initial values for betas

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#11]
We'd like to do warm starts where the underlying data has slightly changed (different rows have been excluded). Providing a way to specify the initial values for the betas would achieve that, because we can then insert the estimated coefficients from the previous run.

**Comment by msuchard** [comment]
This should be implemented now in 1977a1ecfb79872dede4006f0f5f7f2562bdf414 and accessible via:

```R
cyclopsFit <- fitCyclopsModel(cyclopsData,
                              startingCoefficients = values)
```

Also note that it is possible to exclude rows from a fit without regenerating the cyclopsData object via:

```R
cyclopsFit <- fitCyclopsModel(cyclopsData,
                              weights = c(rep(1, lengthIn), rep(0, lengthOut))) # 0 for each row to exclude
```

Let me know if problems remain.
