### ISSUE TITLE
How to enable GPU in the current R package?

### ISSUE THREAD

**Issue by mingcao** [OHDSI/Cyclops#18]
Dear Dr. Suchard, I am a PhD student in U of Texas Biostats, trying to speed up Cyclops using GPU, inspired by your 2013 TOMACS paper. However, I didn't find any guidance on how to enable it in the current package. I tried to uncomment find_package(CUDA) in the CMake file but it seems not working. I am wondering what else should I do? Thank you so much!

**Comment by msuchard** [comment]
I am glad that you're interested in GPU implementations.  Unfortunately, I have not yet ported the GPU work into the current `Cyclops` package.  It exists in an older self-controlled case series only ancestor to `Cyclop`.  @tshaddox should be able to help you navigate the code-base to find what you want.  

In the mean time, @tshaddox and I are very interested in implementing GPU processing across all models in `Cyclops`.  Please do let me know if this is something with which you'd like to help / be involved.

**Comment by mingcao** [comment]
Thank you so much for your reply, Dr. Suchard. It is my honor to have the opportunity to work with you! My undergraduate was CS major and then worked 2yrs in HP as a software engineer. For the last five years, I study Genomics and Biostatistics. My research interest is to combine solid statistical inference with distributed parallel computing like Spark. I actually hesitated a little bit yesterday since not sure whether I still want to go that deep engineering side, but who wants to miss the opportunity to learn from a COPSS winner? : ) So yeah, I will prepare myself for several days and read the three of your 2013 papers carefully. Do you have any suggestion that can get me started?

**Comment by msuchard** [comment]
Branches `gpu-merge` and `gpu-cox` are working towards this end.
