### ISSUE TITLE
Faster computation of confidence intervals

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#25]
Currently, computing the confidence intervals of non-regularized betas takes a long time (often longer than the time needed to create the original fit). When computing the confidence intervals for several variables this can be a bit cumbersome. Is there a way to speed up the computation of CIs? Computing the CI of each variable in a separate thread would already help a lot.

**Comment by msuchard** [comment]
At a minimum, we can use two threads per CI without much trouble, one for each bound search.  More performance will require a GPU port.

**Comment by schuemie** [comment]
Computing each bound in its own thread would really help a lot, especially with the new [SCCS](https://github.com/OHDSI/SelfControlledCaseSeries) package. 

Please? (I can help with testing, but I don't think there's much more I can do to help)

**Comment by msuchard** [comment]
Working on it slowly.  But am on travel with my infectious-disease-hat on until next Friday.

**Comment by schuemie** [comment]
No worries, I'm traveling as well. This would be nice to have when we start doing empirical calibration which I don't see happening until 2016.
