### ISSUE TITLE
Install error on linux ( RHEL 6 and R 3.2 )

### ISSUE THREAD

**Issue by rstarr7** [OHDSI/Cyclops#28]
I am sure I am missing a dependency, but I have no idea what it is.
g++ 4.4.7
R-3.2.3

I tried the downgrade of BH that @msuchard suggested, but it did not help.

'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/tmp/RtmpgDiCmU/devtools19a34d0cb2af/OHDSI-Cyclops-5dea025'  \
  --library='/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘Cyclops’ ...
** libs
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG -I. -Icyclops -DR_BUILD -DDOUBLE_PRECISION -I/usr/local/include -I"/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/Rcpp/include" -I"/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/BH/include" -I"/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include" -I"/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppParallel/include"  -s -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cyclops/CcdInterface.cpp -o cyclops/CcdInterface.o
In file included from cyclops/CyclicCoordinateDescent.h:12,
                 from cyclops/CcdInterface.cpp:29:
cyclops/CompressedDataMatrix.h: In member function ‘void bsccs::CompressedDataMatrix::push_back(IntVectorItr, IntVectorItr, RealVectorItr, RealVectorItr, bsccs::FormatType)’:
cyclops/CompressedDataMatrix.h:304: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(NULL, bsccs::RealVectorPtr&, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:314: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr&, NULL, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:316: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(NULL, NULL, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h: In member function ‘void bsccs::CompressedDataMatrix::replace(int, IntVectorItr, IntVectorItr, RealVectorItr, RealVectorItr, bsccs::FormatType)’:
cyclops/CompressedDataMatrix.h:329: error: no matching function for call to ‘bsccs::CompressedDataMatrix::replace(int&, NULL, bsccs::RealVectorPtr&, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:409: note: candidates are: void bsccs::CompressedDataMatrix::replace(int, bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:336: error: no matching function for call to ‘bsccs::CompressedDataMatrix::replace(int&, bsccs::IntVectorPtr&, NULL, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:409: note: candidates are: void bsccs::CompressedDataMatrix::replace(int, bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:338: error: no matching function for call to ‘bsccs::CompressedDataMatrix::replace(int&, NULL, NULL, bsccs::FormatType&)’
cyclops/CompressedDataMatrix.h:409: note: candidates are: void bsccs::CompressedDataMatrix::replace(int, bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h: In member function ‘void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)’:
cyclops/CompressedDataMatrix.h:348: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(NULL, bsccs::RealVectorPtr&, bsccs::FormatType)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:358: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr&, NULL, bsccs::FormatType)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:360: error: no matching function for call to ‘bsccs::CompressedDataMatrix::push_back(NULL, NULL, bsccs::FormatType)’
cyclops/CompressedDataMatrix.h:344: note: candidates are: void bsccs::CompressedDataMatrix::push_back(bsccs::FormatType)
cyclops/CompressedDataMatrix.h:399: note:                 void bsccs::CompressedDataMatrix::push_back(bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
cyclops/CompressedDataMatrix.h: In member function ‘void bsccs::CompressedDataMatrix::insert(size_t, bsccs::FormatType)’:
cyclops/CompressedDataMatrix.h:370: error: no matching function for call to ‘bsccs::CompressedDataMatrix::insert(__gnu_cxx::__normal_iterator<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> >*, std::vector<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> >, std::allocator<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> > > > >, NULL, bsccs::RealVectorPtr&, bsccs::FormatType)’
cyclops/CompressedDataMatrix.h:366: note: candidates are: void bsccs::CompressedDataMatrix::insert(size_t, bsccs::FormatType)
cyclops/CompressedDataMatrix.h:421: note:                 void bsccs::CompressedDataMatrix::insert(__gnu_cxx::__normal_iterator<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> >*, std::vector<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> >, std::allocator<std::unique_ptr<bsccs::CompressedDataColumn, std::default_delete<bsccs::CompressedDataColumn> > > > >, bsccs::IntVectorPtr, bsccs::RealVectorPtr, bsccs::FormatType)
In file included from cyclops/CyclicCoordinateDescent.h:13,
                 from cyclops/CcdInterface.cpp:29:
cyclops/ModelData.h: In function ‘typename Itr::value_type bsccs::quantile(Itr, Itr, double)’:
cyclops/ModelData.h:297: error: ‘floor’ is not a member of ‘std’
cyclops/ModelData.h:297: error: unable to deduce ‘const auto’ from ‘<expression error>’
cyclops/ModelData.h:298: error: ‘ceil’ is not a member of ‘std’
cyclops/ModelData.h:298: error: unable to deduce ‘const auto’ from ‘<expression error>’
In file included from cyclops/priors/JointPrior.h:14,
                 from cyclops/CyclicCoordinateDescent.h:15,
                 from cyclops/CcdInterface.cpp:29:
cyclops/priors/CovariatePrior.h: In member function ‘virtual const std::string bsccs::priors::FusedLaplacePrior::getDescription() const’:
cyclops/priors/CovariatePrior.h:256: error: expected initializer before ‘:’ token
cyclops/priors/CovariatePrior.h:260: error: expected primary-expression before ‘return’
cyclops/priors/CovariatePrior.h:260: error: expected ‘)’ before ‘return’
In file included from cyclops/CyclicCoordinateDescent.h:15,
                 from cyclops/CcdInterface.cpp:29:
cyclops/priors/JointPrior.h: In member function ‘void bsccs::priors::JointPrior::addVarianceParameters(const std::vector<std::shared_ptr<double>, std::allocator<std::shared_ptr<double> > >&)’:
cyclops/priors/JointPrior.h:53: error: expected initializer before ‘:’ token
cyclops/priors/JointPrior.h:56: error: expected primary-expression before ‘}’ token
cyclops/priors/JointPrior.h:56: error: expected ‘;’ before ‘}’ token
cyclops/priors/JointPrior.h:56: error: expected primary-expression before ‘}’ token
cyclops/priors/JointPrior.h:56: error: expected ‘)’ before ‘}’ token
cyclops/priors/JointPrior.h:56: error: expected primary-expression before ‘}’ token
cyclops/priors/JointPrior.h:56: error: expected ‘;’ before ‘}’ token
cyclops/priors/JointPrior.h: In member function ‘std::vector<double, std::allocator<double> > bsccs::priors::JointPrior::getVariance() const’:
cyclops/priors/JointPrior.h:65: error: expected initializer before ‘:’ token
cyclops/priors/JointPrior.h:68: error: expected primary-expression before ‘return’
cyclops/priors/JointPrior.h:68: error: expected ‘;’ before ‘return’
cyclops/priors/JointPrior.h:68: error: expected primary-expression before ‘return’
cyclops/priors/JointPrior.h:68: error: expected ‘)’ before ‘return’
cyclops/priors/JointPrior.h: In member function ‘virtual const std::string bsccs::priors::MixtureJointPrior::getDescription() const’:
cyclops/priors/JointPrior.h:96: error: expected initializer before ‘:’ token
cyclops/priors/JointPrior.h:99: error: expected primary-expression before ‘return’
cyclops/priors/JointPrior.h:99: error: expected ‘;’ before ‘return’
cyclops/priors/JointPrior.h:99: error: expected primary-expression before ‘return’
cyclops/priors/JointPrior.h:99: error: expected ‘)’ before ‘return’
cyclops/priors/JointPrior.h: In member function ‘virtual bool bsccs::priors::MixtureJointPrior::getSupportsKktSwindle() const’:
cyclops/priors/JointPrior.h:148: error: expected initializer before ‘:’ token
cyclops/priors/JointPrior.h:154: error: expected primary-expression at end of input
cyclops/priors/JointPrior.h:154: error: expected ‘;’ at end of input
cyclops/priors/JointPrior.h:154: error: expected primary-expression at end of input
cyclops/priors/JointPrior.h:154: error: expected ‘)’ at end of input
cyclops/priors/JointPrior.h:154: error: expected statement at end of input
cyclops/priors/JointPrior.h:154: error: expected ‘}’ at end of input
cyclops/priors/JointPrior.h:154: warning: no return statement in function returning non-void
In file included from /home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/Core:288,
                 from /home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/Dense:1,
                 from cyclops/CyclicCoordinateDescent.h:18,
                 from cyclops/CcdInterface.cpp:29:
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h: In constructor ‘Eigen::DenseStorage<T, -0x00000000000000001, -0x00000000000000001, -0x00000000000000001, _Options>::DenseStorage(Eigen::DenseStorage<T, -0x00000000000000001, -0x00000000000000001, -0x00000000000000001, _Options>&&)’:
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h:281: error: ‘nullptr’ was not declared in this scope
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h: In constructor ‘Eigen::DenseStorage<T, -0x00000000000000001, _Rows, -0x00000000000000001, _Options>::DenseStorage(Eigen::DenseStorage<T, -0x00000000000000001, _Rows, -0x00000000000000001, _Options>&&)’:
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h:339: error: ‘nullptr’ was not declared in this scope
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h: In constructor ‘Eigen::DenseStorage<T, -0x00000000000000001, -0x00000000000000001, _Cols, _Options>::DenseStorage(Eigen::DenseStorage<T, -0x00000000000000001, -0x00000000000000001, _Cols, _Options>&&)’:
/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/RcppEigen/include/Eigen/src/Core/DenseStorage.h:393: error: ‘nullptr’ was not declared in this scope
In file included from cyclops/drivers/GridSearchCrossValidationDriver.h:11,
                 from cyclops/CcdInterface.cpp:48:
cyclops/drivers/AbstractCrossValidationDriver.h: At global scope:
cyclops/drivers/AbstractCrossValidationDriver.h:25: error: ‘nullptr’ was not declared in this scope
cyclops/CcdInterface.cpp: In member function ‘double bsccs::CcdInterface::profileModel(bsccs::CyclicCoordinateDescent*, bsccs::ModelData*, const bsccs::ProfileVector&, bsccs::ProfileInformationMap&, int, double, bool, bool)’:
cyclops/CcdInterface.cpp:333: error: expected primary-expression before ‘[’ token
cyclops/CcdInterface.cpp:334: warning: left-hand operand of comma has no effect
cyclops/CcdInterface.cpp:335: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:335: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:335: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:336: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:336: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:336: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:336: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:336: warning: right-hand operand of comma has no effect
cyclops/CcdInterface.cpp:337: error: expected primary-expression before ‘const’
cyclops/CcdInterface.cpp:337: error: expected primary-expression before ‘*’ token
cyclops/CcdInterface.cpp:337: error: unable to deduce ‘auto’ from ‘<expression error>’
cyclops/CcdInterface.cpp:337: error: expected ‘,’ or ‘;’ before ‘{’ token
cyclops/CcdInterface.cpp:268: warning: unused variable ‘time2’
cyclops/CcdInterface.cpp:333: warning: unused variable ‘getBound’
cyclops/CcdInterface.cpp:719: error: expected ‘}’ at end of input
cyclops/CcdInterface.cpp:719: warning: no return statement in function returning non-void
cyclops/CcdInterface.cpp: At global scope:
cyclops/CcdInterface.cpp:719: error: expected ‘}’ at end of input
make: *** [cyclops/CcdInterface.o] Error 1
ERROR: compilation failed for package ‘Cyclops’
* removing ‘/home/rstarr7/R/x86_64-redhat-linux-gnu-library/3.2/Cyclops’
Error: Command failed (1)

**Comment by msuchard** [comment]
I suspect this is a gcc 4.4 issue.  This compiler does not support c++11.  Keep in mind that even R on Windoz uses gcc 4.6.3, so that's probably a minimal requirement on the compiler.  The following is one such c++11 error example: `error: ‘nullptr’ was not declared`

Downgrading BH will have no effect here, since `Cyclops` now includes its own copy of the relevant (older) boost headers.

**Comment by rstarr7** [comment]
Thanks Marc!  I will work on upgrading gcc.  We are running RHEL 6 and their slow adoption new things is painful.

**Comment by msuchard** [comment]
You could run a Docker instance of something newer, or use the `ohdsi/development` container.
