### ISSUE TITLE
Rtools 3.4

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Cyclops#29]
If I install the latest Rtools version 3.4 the install of Cylops in R still wants 3.3

**Comment by msuchard** [comment]
I am unclear what "still wants" means here.  There are no direct dependencies between the Cyclops source code and RTools (beyond `gcc >= 4.6.3`).  I suspect there are other packages for which you have already compiled with the older compiler that no longer link when some packages are compiled with the newer compiler.

What is the error message you are getting?   And steps did you take to generate that message?   Plus, further info about your system (R version, package versions, etc.) would be helpful.

**Comment by msuchard** [comment]
You may want to also try `devtools::find_rtools()`.

**Comment by PRijnbeek** [comment]
Ok let me be more clear then :)

1. I installed the latest version of Rtools which is currently 3.4
2. I run install_github("ohdsi/Cyclops") in R

results: popup "Install Build Tools" Building R package from source requires installation of additional build tools. Do you want to install the additional tools now?"

It then installs Rtools 3.3 and the install_github works fine afterwards. I would expect Rtools3.4 would be enough since:  
devtools::find_rtools()
[1] TRUE

I reproduced this by removing Rtools 3.3 and do the whole thing again.

Info:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by msuchard** [comment]
Pop-up error message is from `devtools`.  Not likely a `Cyclops` issues.  @PRijnbeek, please re-open if this issue remains after Rtools 3.4 becomes default.
