### ISSUE TITLE
error message when running Cyclops

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Cyclops#30]
When i run Cyclops i get this message:

Error in ifelse(!is.null(index$index), max(index$index), 1): object 'index' not found

I did a fresh install from github. (version 1.2.1-1)

Any ideas how to solve this? 

Thanks.

**Comment by msuchard** [comment]
That does not look like any `Cyclops` code I can remember.   Can you provide example code to generate the error?

**Comment by PRijnbeek** [comment]
<img width="557" alt="screenshot 2016-08-03 20 08 56" src="https://cloud.githubusercontent.com/assets/7252105/17386181/274b705c-59b6-11e6-8bd9-a3c239b9e40c.png">

It happens in the call shown in the screenshot. 

I can try if i can reproduce it on another machine if that helps. I could share the cyclopsData, prior and control R objects as well if you want by email. It is a small simulated dataset.

**Comment by PRijnbeek** [comment]
The issue was related to a bug in the control function settings (fold was calculated incorrectly).

Therefore the control function was made a promise evaluation
