### ISSUE TITLE
Receiving warnings when building from source in R 3.3.1

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Cyclops#33]
I'm seeing warnings during installing cyclops (as a dependency of CohortMethod) from source using the following command:

`
install_git("OHDSI\CohortMethod")
`

The warning is:
```text
RcppCyclopsInterface.cpp: In member function 'bsccs::priors::JointPriorPtr bsccs::RcppCcdInterface::makePrior(const std::vector<std::basic_string<char> >&, const std::vector<double>&, const ProfileVector&, const HierarchicalChildMap&, const NeighborhoodMap&)':
RcppCyclopsInterface.cpp:581:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         && basePriorName.size() == length
                                 ^
RcppCyclopsInterface.cpp:582:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         && baseVariance.size() == length) {
                                ^
````

I think the warning is harmless but could this be cleaned up?

-Chris

**Comment by msuchard** [comment]
Yes, cleaning up the Windows compile warnings is a great idea.  When might I except a pull request? :-)

**Comment by chrisknoll** [comment]
Sure, trust me to do the C++ code....good idea.

**Comment by chrisknoll** [comment]
Here you go: #34.  Interesting that non-windows compilers don't know the difference between signed and unsigned ints?

**Comment by msuchard** [comment]
RTools on Windows uses a very old compiler.  Newer compilers deduce that `length` could never have been negative in the first place.
