### ISSUE TITLE
Report seed used in cross-validation

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#35]
This would be a nice-to-have: After fitting a model, could the cyclopFit object report on the random seed used to randomize the folds? The use case is when we've fitted a model, and later want to rerun our analysis we can choose to use the same seed so that if the data hasn't changed, the result will be the same.

**Comment by msuchard** [comment]
No problem ... this is all handled on the `R` side.

**Comment by msuchard** [comment]
Should now be implemented [here](https://github.com/OHDSI/Cyclops/blob/6401666875c86967688ae556d2d423a86a790bc6/tests/testthat/test-cv.R#L198-L208).
