### ISSUE TITLE
Cyclops error in createPs function of CohortMethod package

### ISSUE THREAD

**Issue by aperotte** [OHDSI/Cyclops#38]
When running createPs on our local instance from the CohortMethod package single study vignette (and when running our own studies), we get the following error when run against some of our databases (for others it works fine):

Error in .loadCyclopsDataMultipleX(object, covariateId, rowId, covariateValue,  :
    Repeated row-column entry at 9 - 1008

Do you have any insight as to why this might be happening?  Any hints would be greatly appreciated.

**Comment by schuemie** [comment]
For each rowId (ie. person) each covariateId should appear only once, and this seem to not be the case for your data. 

If I look at the [SQL in the single study vignette for defining the exposure cohorts](https://github.com/OHDSI/CohortMethod/blob/master/vignettes/SingleStudies.Rmd#L86), I see it assumes records in the drug_era table are not duplicated. Could you check whether in your data this assumption is violated (for the exposures of interest)? 

Something like
```sql
SELECT person_id,
  drug_era_start_date,
  drug_concept_id 
FROM drug_era
WHERE drug_concept_id IN (1118084, 1124300) -- Diclofenac, celecoxib
GROUP BY person_id,
  drug_era_start_date,
  drug_concept_id 
HAVING COUNT(*) > 1
```
should return 0 rows

**Comment by aperotte** [comment]
Thank you!  That was indeed the issue.
