### ISSUE TITLE
Using old control object throws uninformative error

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#39]
We tend to store the `control` object as part of our study settings. Control objects created using Cyclops versions < 2.0.0 cause an uninformative error to be thrown in versions >= 2.0.0:

```r
library(Cyclops)
sim <- simulateCyclopsData()
cyclopsData <- convertToCyclopsData(sim$outcomes, sim$covariates, modelType = "cox")
control <- createControl()
# Older control object doesn't have algorithm variable:
control$algorithm <- NULL
fit <- fitCyclopsModel(cyclopsData, control = control)
# Error in if (is.na(control$algorithm)) { : argument is of length zero
```

Recommended behavior: if algorithm variable not found, assume "ccd". Alternative: throw meaningful error message stating the control object is out of date.

**Comment by msuchard** [comment]
Should now be fixed.   See: cd398d2b5627b0ef09cb22cd5069d637d4151a97
