### ISSUE TITLE
issue with survfit()

### ISSUE THREAD

**Issue by jreps** [OHDSI/Cyclops#50]
I'm getting an error: "Variable -2147483648 is unknown"

debugging it seems to be caused by:
survfit() -> meanLinearPredictor() -> summary.cyclopsData() -> reduce() -> .cyclopsSum()

the same error occurs for .cyclopsSumByStratum() 

could this be an int64 issue?

**Comment by msuchard** [comment]
This is almost surely an int64 issue.  I'll look into it.  If you could provide a small code snippet that causes the error, that would be quite helpful.

**Comment by msuchard** [comment]
@jreps -- this following does cause an error (both in `Cyclops` with the first `covariateId` that I need to fix and in `bit64` in representing the 2nd #).  But, I think you are experiencing something different.  Can you add to this code snippet?


```
test_that("Check int64 reductions", {
    set.seed(123)

    data <- simulateCyclopsData(nstrata = 1,
                                nrows = 1000,
                                ncovars = 5,
                                model="logistic")

    # using int64
    data$outcomes$rowId <- bit64::as.integer64(data$outcomes$rowId)
    data$covariates$rowId <- bit64::as.integer64(data$covariates$rowId)
    data$covariates$covariateId <- bit64::as.integer64(data$covariates$covariateId)
    data$covariates$covariateId[1] <- bit64::as.integer64( "9223372036854775807")
    data$covariates$covariateId[2] <- bit64::as.integer64("18446744073709551615")

    cyclopsData64 <- convertToCyclopsData(data$outcomes,data$covariates, modelType = "lr", addIntercept = TRUE)
    data$covariates$covariateId[1:3]
    summary(cyclopsData64)
})
```

**Comment by jreps** [comment]
I think the summary() issue with your data example is the same as in the summary() issue with the fitted model I saw yesterday:

`
set.seed(123)
  
  data <- simulateCyclopsData(nstrata = 1,
                              nrows = 1000,
                              ncovars = 5,
                              model="logistic")
  
  # using int64
  data$outcomes$rowId <- bit64::as.integer64(data$outcomes$rowId)
  data$covariates$rowId <- bit64::as.integer64(data$covariates$rowId)
  data$covariates$covariateId <- bit64::as.integer64(data$covariates$covariateId)
  data$covariates$covariateId[1] <- bit64::as.integer64( "9223372036854775807")
  data$covariates$covariateId[2] <- bit64::as.integer64("18446744073709551615")
  
  cyclopsData64 <- convertToCyclopsData(data$outcomes,data$covariates, modelType = "lr", addIntercept = TRUE)
  data$covariates$covariateId[1:3]
  
  fit <- Cyclops::fitCyclopsModel(cyclopsData64, prior = createPrior("laplace", useCrossValidation = TRUE)) 
  
  meanLinearPredictor(fit) # seems to give the same error 
`

**Comment by msuchard** [comment]
This commit (`develop` branch) should fix the issue (and probably introduce many new ones):

https://github.com/OHDSI/Cyclops/commit/cdf3aa545b591d9f2cadd7f70cb37756df82a031
