### ISSUE TITLE
Issue with covertToCyclopsData - ORDER By is Ignored in sub queries

### ISSUE THREAD

**Issue by azimov** [OHDSI/Cyclops#52]
In CohortMethod when calling `fitOutcomeModel`  the following warning is thrown:

```
ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
Backtrace:
  1. CohortMethod::runCmAnalyses(...) test-eunomia.R:116:2
  2. ParallelLogger::clusterApply(cluster, modelsToFit, doFitOutcomeModelPlus) /Users/jamie/PycharmProjects/CohortMethod/R/RunAnalyses.R:426:6
  3. base::lapply(x, fun, ...)
  4. CohortMethod:::FUN(X[[i]], ...)
  6. CohortMethod::fitOutcomeModel(...)
  8. Cyclops:::convertToCyclopsData.tbl_dbi(...)
  9. Andromeda::batchApply(covariates, loadCovariates, batchSize = 1e+05)
 11. dbplyr:::sql_render.tbl_lazy(tbl, connection)
 13. dbplyr:::sql_render.op(query$ops, con = con, ..., subquery = subquery)
 15. dbplyr:::sql_render.select_query(qry, con = con, ..., subquery = subquery)
 24. dbplyr:::sql_render.join_query(query$from, con, ..., subquery = TRUE)
 33. dbplyr:::sql_render.tbl_lazy(query$y, con, ..., subquery = TRUE)
 35. dbplyr:::sql_render.op(query$ops, con = con, ..., subquery = subquery)
 37. dbplyr:::sql_render.select_query(qry, con = con, ..., subquery = subquery)
 38. dbplyr:::dbplyr_query_select(...)
 39. dbplyr:::dbplyr_fallback(con, "sql_select", ...)
 41. dbplyr:::sql_select.DBIConnection(con, ...)
 43. dbplyr:::sql_query_select.DBIConnection(...)
 45. dbplyr:::sql_clause_order_by(con, order_by, subquery, limit)
 46. dbplyr:::warn_drop_order_by()

````

This appears to be a problem with how cyclops is calling Andromeda. Reproducible in the unit tests found [here]( https://github.com/OHDSI/CohortMethod/blob/a85f385ba2cf6a1e3d53fcc95982a82060c27430/tests/testthat/test-parameterSweep.R#L235)

**Comment by msuchard** [comment]
@schuemie and I were just discussing this here: https://github.com/OHDSI/Andromeda/issues/25

1. this warning behavior is relatively new (i.e., I have not seen this warning before today, although I have not looked in several months)
2. am not sure if this really is an issue or not
3. i could definitely use some help in tracking down the issue

**Comment by schuemie** [comment]
Found it. Under specific conditions `outcomes` is being sorted [here](https://github.com/OHDSI/Cyclops/blob/develop/R/NewDataConversion.R#L314), and then joined to `covariates` [here](https://github.com/OHDSI/Cyclops/blob/develop/R/NewDataConversion.R#L317), at which time the sorting is lost (in the join, not in the `outcomes` object). This has no effect on the final result, but the warning is annoying. It can be fixed by joining before applying the sort on `outcomes`.

**Comment by msuchard** [comment]
Great work, @schuemie !
