### ISSUE TITLE
'NAs produced by integer overflow' when calling `confint()`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#54]
In [various places](https://github.com/OHDSI/Cyclops/blob/75ab6624719e7bf193e744ad6061962c7a008d5c/R/ModelFit.R#L781-L795) in `confint()` the covariate ID is cast to a (32-bit) integer, causing the message 'NAs produced by integer overflow' to be generated when the covariate ID does not fit in a 32-bit integer. Many covariate IDs (like those generated by the FeatureExtraction package) do not fit in a 32-bit integer, but are allowed in Cyclops.

**Comment by msuchard** [comment]
I believe I fixed this in several commits during the hack-a-thon from b2c1f3cd1c6f6815028d8506ff11073af711d2f0 through 70ef8424fa9c6b226cfd0aa15cbb1225f97dd233 in `develop` branch.

Can you provide a short example of the incorrect behavior and I'll happily fix it "better"?

**Comment by schuemie** [comment]
Ah, no, you're right. This is already fixed in `develop`.

**Comment by msuchard** [comment]
that's what friends are for: solving your problems before you even know they exist.
