### ISSUE TITLE
Create new release?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Cyclops#61]
For several months now, when using Cyclops for example in CohortMethod, I get the following warnings:

```r
Warning messages:
1: ORDER BY is ignored in subqueries without LIMIT
i Do you need to move arrange() later in the pipeline or use window_order() instead? 
2: In as.integer.integer64(parm) : NAs produced by integer overflow
```

I think all of these have already been address in the various develop branches of Cyclops. Would it be possible to create a Cyclops release just to keep the console clean?

**Comment by msuchard** [comment]
I just merged `develop` --> `main`.    If you can confirm that 5e9437161f2b462d978102772f5eb78bd48fa1fd (current HEAD of `main`) solves your issues, then I will submit to CRAN as new v3.1.3.

**Comment by msuchard** [comment]
@schuemie -- just pinging to check on that confirmation (above).  are we good to go?

**Comment by schuemie** [comment]
Thanks!
